spring:
  application:
    name: Edusync
  datasource:
    url: jdbc:mysql://localhost:3306/edusync
    username: <your-username>
    password: <your-password>
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
application:
  security:
    jwt:
      secret-key: <your-secret>
      expiration: 0
      refresh-token:
        expiration: 0
